### ISSUE TITLE
Error thrown by cordova-plugin-add-swift-support

### ISSUE THREAD

**Issue by msudol** [emcniece/cordova-plugin-wifiinfo#2]
#1 I really like the premise of this plugin - a nice lightweight connection info for the currently connected wifi... the other plugins are so bulky and include management and scanning for other nodes...  only issue is, I can't get this to work..  

 #```
Installing "cordova-plugin-wifiinfo" for android
Installing "cordova-plugin-add-swift-support" for android
(node:6032) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cordova/platform_metadata'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)  
... 
(node:6032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

It looks like your plugin is trying to add that plugin, and it is failing.

**Comment by emcniece** [comment]
Interesting, my bet is this is a deficiency with the latest Cordova or `cordova-android`. Can you provide some environment info like `ionic info` and `cordova info`, OS + version, etc?

I might have some time to test this today or tomorrow.

**Comment by emcniece** [comment]
Oh, hey:

```
Installing "cordova-plugin-add-swift-support" for android
(node:6032) UnhandledPromiseRejectionWarning: Error: Cannot find module 
```

Of course - you don't have an iOS project added, right?

![screen shot 2018-05-14 at 11 38 23 am](https://user-images.githubusercontent.com/1182187/40016498-5a334e04-576b-11e8-989f-531c500c2a4e.png)

The `cordova-plugin-add-swift-support` is iOS-only, maybe it's having trouble finding the Android version? Quick guess.

**Comment by msudol** [comment]
Yes, right now i'm building for Phonegap online build, and testing in CLI with only Android.. don't have my iOS developer license yet.

cordova cli version is 8.0.0 in my env, but i'm building for 7.0.1 which is what Phonegap online build uses.

**Comment by emcniece** [comment]
Alright, good to know. Out of curiosity, if you add the iOS platform (don't need to build, just `cordova platform add ios`) and then try re-running the plugin install does it work?

**Comment by msudol** [comment]
I'll let you know, going to have to rebuild my local env - looks like need to upgrade to target android 6.3.0 which means I need have gradle installed...  once I revamp my env I'll let you know how it goes.

**Comment by msudol** [comment]
Must be my build environment because I just went and built on Phonegap Online Build and it worked just fine.

**Comment by emcniece** [comment]
Good to know. Feel free to re-open if it happens again in the future!
