### ISSUE TITLE
Timeline on a working iOS version

### ISSUE THREAD

**Issue by msudol** [emcniece/cordova-plugin-wifiinfo#3]
I've done a lot of research on how the API to get RSSI is a private API and Apple won't allow on the app store, but my app is internal use only and we're going to deploy differently... definitely want to be able to get RSSI on iOS, what do you think it would take to get that done?

**Comment by emcniece** [comment]
Perhaps this could be added with [Apple80211Functions](https://code.google.com/archive/p/iphone-wireless/wikis/Apple80211Functions.wiki) (from [Apple80211GetInfoCopy](https://code.google.com/archive/p/iphone-wireless/wikis/Apple80211GetInfoCopy.wiki) specifically).

As you note, this would prevent the app from being approved for use in the app store. I'd prefer to keep this plugin small, focused and deployable.

So "Timeline on a working iOS version" is... infinity? 😆

**Comment by msudol** [comment]
Are you available for hire for a private fork of this repo then?

**Comment by emcniece** [comment]
@msudol I might be able to fit this in over the next month. Fire me an email at emcniece@gmail.com and let's chat.

**Comment by emcniece** [comment]
@msudol looks like we're building a new plugin for the RSSI feature. Are we clear to close this ticket?

**Comment by msudol** [comment]
Sounds good.
