### ISSUE TITLE
Plugin to connect to LAN 

### ISSUE THREAD

**Issue by SaileshMS** [emcniece/cordova-plugin-wifiinfo#4]
Does this plugin helps to connect my Cordova app to LAN ( DHCP or static ip) connection

**Comment by emcniece** [comment]
No - it only fetches information about the Wifi network currently in use.

**Comment by SaileshMS** [comment]
Is there any way to make connection from Cordova app to static IP

**Comment by emcniece** [comment]
Sure. You don't need Cordova to do that - just Javascript. You can use websockets or cross-domain requests.

**Comment by SaileshMS** [comment]
Actually what's required is to prompt user to type in  ip, gateway , DNS in a page  and make connection to LAN via Cordova app.? Like we do in pc

**Comment by emcniece** [comment]
Your requirements are possible, but this plugin will not be of much help. Closing as off-topic.
